version: '3'

services:
  keycloak-db:
    image: mysql:8.0
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: ipiel
    command: mysqld --sql_mode=""

  ct-keycloak-iam:
    depends_on:
      - keycloak-db
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8888:8888
      - 8080:8080
      - 8443:8443
      - 9990:9990
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 3306
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ipiel
      KC_DB_URL_PROPERTIES: ?useSSL=false&allowPublicKeyRetrieval=true

      # Uncomment when in production
      # KEYCLOAK_IMPORT: /opt/jboss/keycloak_install_stage/realms/ct-realm-prod.json
      KEYCLOAK_ADMIN: keycloak.admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak.admin

      KC_HOSTNAME_STRICT: false
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

      DEBUG_PORT: 8888
      PROXY_ADDRESS_FORWARDING: 'true'